version: 2.1
orbs:
  newman: postman/newman@1.0.0
  slack: circleci/slack@4.12.5
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./ulab2.json
          environment: ./ulab.env.json